--- #YAML:1.0
name:               Test-Valgrind
version:            0.08
abstract:           Test Perl code through valgrind.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    Config:               0
    ExtUtils::MakeMaker:  0
    File::Spec:           0
build_requires:
    ExtUtils::MakeMaker:  0
    File::Copy:           0
    Test::More:           0
requires:
    Carp:                 0
    Exporter:             0
    Fcntl:                0
    perl:                 5.006
    Perl::Destruct::Level:  0
    POSIX:                0
    Test::Builder:        0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Test-Valgrind
    homepage:    http://search.cpan.org/dist/Test-Valgrind/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/perl/modules/Test-Valgrind.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    DynaLoader:  0
    XSLoader:    0
